"use client";

import { ArrowDown, ArrowUpRight, Layers, ScanLine, Link2, Bookmark, WandSparkles, ShieldCheck, Activity, CalendarDays, Check, CheckCircle2, ChevronRight, Clock3, Dumbbell, ImagePlus, ListChecks, MapPin, RefreshCw, ShoppingBasket, Sparkles, UploadCloud, UtensilsCrossed, X } from "lucide-react";
import { useEffect, useRef, useState } from "react";
import { Badge } from "@/components/ui/badge";
import { Button } from "@/components/ui/button";
import { Progress } from "@/components/ui/progress";
import { Tabs, TabsContent, TabsList, TabsTrigger } from "@/components/ui/tabs";

type ActionKind = "event" | "recipe" | "workout" | "other";
type ActionItem = { id:string; kind:ActionKind; title:string; summary:string; date:string; time:string; location:string; checklist:string[]; checked:boolean[]; missingInformation:string[]; confidence:number; source:string; completed:boolean; savedAt:string };
const MAX_IMAGE_BYTES=15*1024*1024;

const samples: Record<Exclude<ActionKind,"other">,ActionItem> = {
  event:{id:"sample-event",kind:"event",title:"Sunset Yoga on the Lawn",summary:"A free outdoor reset with guided yoga, music, and refreshments.",date:"2026-09-17",time:"18:30",location:"Urbanovsky Park, Texas Tech",checklist:["Add the event to my calendar","Bring a mat and water","Invite one friend"],checked:[false,false,false],missingInformation:[],confidence:.96,source:"Instagram screenshot",completed:false,savedAt:new Date().toISOString()},
  recipe:{id:"sample-recipe",kind:"recipe",title:"15-minute chili crisp noodles",summary:"A fast pantry dinner with noodles, chili crisp, soy sauce, lime, and a jammy egg.",date:"",time:"15 min",location:"",checklist:["Noodles","2 eggs","Chili crisp","Soy sauce","1 lime","Scallions"],checked:[false,false,false,false,false,false],missingInformation:["Exact serving size"],confidence:.91,source:"TikTok screenshot",completed:false,savedAt:new Date().toISOString()},
  workout:{id:"sample-workout",kind:"workout",title:"No-equipment study break",summary:"A short full-body circuit designed to break up a long study session.",date:"",time:"12 min",location:"Anywhere",checklist:["10 bodyweight squats","8 incline push-ups","20-second plank","Repeat for 3 rounds"],checked:[false,false,false,false],missingInformation:["Rest time between rounds"],confidence:.89,source:"Reels screenshot",completed:false,savedAt:new Date().toISOString()}
};
const meta={event:{label:"Event",icon:CalendarDays,accent:"#7C5CFF",soft:"#EEEAFE"},recipe:{label:"Recipe",icon:UtensilsCrossed,accent:"#FF7A55",soft:"#FFF0EA"},workout:{label:"Workout",icon:Dumbbell,accent:"#13A87D",soft:"#E5F8F1"},other:{label:"Action",icon:Sparkles,accent:"#2477E8",soft:"#E9F2FF"}};

function normalize(raw:Partial<ActionItem>,source:string):ActionItem{const list=Array.isArray(raw.checklist)?raw.checklist.filter(Boolean):[];return{id:crypto.randomUUID(),kind:raw.kind&&raw.kind in meta?raw.kind:"other",title:raw.title||"Untitled action",summary:raw.summary||"Review the source and choose your next step.",date:raw.date||"",time:raw.time||"",location:raw.location||"",checklist:list,checked:list.map(()=>false),missingInformation:Array.isArray(raw.missingInformation)?raw.missingInformation:[],confidence:Math.min(1,Math.max(0,Number(raw.confidence)||0)),source,completed:false,savedAt:new Date().toISOString()}}
function escapeIcs(v:string){return v.replace(/\\/g,"\\\\").replace(/\n/g,"\\n").replace(/,/g,"\\,").replace(/;/g,"\\;")}
function exportCalendar(item:ActionItem){if(!item.date)return;const start=`${item.date.replaceAll("-","")}T${(item.time||"12:00").replace(":","")}00`;const content=["BEGIN:VCALENDAR","VERSION:2.0","PRODID:-//FeedForward//Action Calendar//EN","BEGIN:VEVENT",`UID:${item.id}@feedforward`,`DTSTART:${start}`,`SUMMARY:${escapeIcs(item.title)}`,`DESCRIPTION:${escapeIcs(item.summary)}`,`LOCATION:${escapeIcs(item.location)}`,"END:VEVENT","END:VCALENDAR"].join("\r\n");const url=URL.createObjectURL(new Blob([content],{type:"text/calendar"}));const a=document.createElement("a");a.href=url;a.download=`${item.title.toLowerCase().replace(/[^a-z0-9]+/g,"-")}.ics`;a.click();URL.revokeObjectURL(url)}

function ActionCard({item,onToggleStep,onComplete,onRemove}:{item:ActionItem;onToggleStep?:(i:number)=>void;onComplete?:()=>void;onRemove?:()=>void}){const m=meta[item.kind],Icon=m.icon,done=item.checked.filter(Boolean).length;const eventDate=item.kind==="event"&&item.date?new Date(`${item.date}T12:00:00`):null;const validDate=eventDate&&!Number.isNaN(eventDate.getTime())?eventDate:null;return <article className={`action-card action-card--${item.kind} ${item.completed?"is-complete":""}`}>
  <div className="action-card__top">{validDate?<div className="event-date"><span>{validDate.toLocaleDateString("en-US",{month:"short"})}</span><strong>{validDate.getDate()}</strong><small>{validDate.toLocaleDateString("en-US",{weekday:"short"})}</small></div>:<div className="kind-mark"><Icon/></div>}<div className="min-w-0 flex-1"><div className="mb-2 flex flex-wrap items-center gap-2"><Badge className="border-0">{m.label}</Badge><span className="source-label">{item.source}</span></div><h2>{item.title}</h2></div>{onRemove&&<Button variant="ghost" size="icon-sm" aria-label="Remove action" onClick={onRemove} className="remove-button"><X/></Button>}</div>
  <p className="action-summary">{item.summary}</p>
  {(item.date||item.time||item.location)&&<div className={`detail-grid ${item.kind==="event"?"event-details":""}`}>{item.date&&<span><CalendarDays/>{new Date(`${item.date}T12:00:00`).toLocaleDateString(undefined,{month:"short",day:"numeric",year:"numeric"})}</span>}{item.time&&<span><Clock3/>{item.time}</span>}{item.location&&<span><MapPin/>{item.location}</span>}</div>}
  <div className="checklist-head"><span>{item.kind==="recipe"?"Shopping list":item.kind==="workout"?"Routine":"Next steps"}</span><span>{done}/{item.checklist.length}</span></div>
  <div className="checklist">{item.checklist.map((step,i)=><button key={`${step}-${i}`} onClick={()=>onToggleStep?.(i)} className={item.checked[i]?"checked":""} disabled={!onToggleStep}><span className="check-box">{item.checked[i]&&<Check/>}</span><span>{step}</span></button>)}</div>
  {item.missingInformation.length>0&&<p className="verify-note"><Sparkles/>Verify: {item.missingInformation.join(" · ")}</p>}
  <div className="action-footer"><div className="confidence"><div><span>Extraction confidence</span><strong>{Math.round(item.confidence*100)}%</strong></div><Progress value={item.confidence*100}/></div><div className="flex gap-2">{item.kind==="event"&&item.date&&<Button variant="outline" onClick={()=>exportCalendar(item)}><CalendarDays/>Add to calendar</Button>}{onComplete&&<Button onClick={onComplete} className="complete-button" disabled={item.completed}>{item.completed?<><CheckCircle2/>Done</>:<>Complete <ChevronRight/></>}</Button>}</div></div>
  </article>}

export default function Home(){const [actions,setActions]=useState<ActionItem[]>([]);const [current,setCurrent]=useState<ActionItem|null>(null);const [preview,setPreview]=useState<string|null>(null);const [fileName,setFileName]=useState("");const [loading,setLoading]=useState(false);const [dragging,setDragging]=useState(false);const [message,setMessage]=useState("");const [hydrated,setHydrated]=useState(false);const [captureMode,setCaptureMode]=useState<"photo"|"link">("photo");const [link,setLink]=useState("");const activeRequest=useRef<AbortController|null>(null);
  // Restore browser-only storage after hydration; server rendering starts with an empty board.
  // eslint-disable-next-line react-hooks/set-state-in-effect
  useEffect(()=>{try{const saved=JSON.parse(localStorage.getItem("feedforward-actions")||"[]");if(Array.isArray(saved))setActions(saved)}catch{}finally{setHydrated(true)}},[]);
  // Surface storage failures instead of silently losing the user’s saved plans.
  // eslint-disable-next-line react-hooks/set-state-in-effect
  useEffect(()=>{if(hydrated){try{localStorage.setItem("feedforward-actions",JSON.stringify(actions))}catch{setMessage("Your browser could not save these actions. Keep this tab open to retain them.")}}},[actions,hydrated]);
  useEffect(()=>{const context=(document as Document&{modelContext?:{registerTool?:(tool:unknown,options?:{signal:AbortSignal})=>void|Promise<void>}}).modelContext;if(!context?.registerTool)return;const lifecycle=new AbortController();void Promise.resolve(context.registerTool({name:"open_feedforward_demo",title:"Open FeedForward demo",description:"Open a representative event, recipe, or workout action.",inputSchema:{type:"object",properties:{kind:{type:"string",enum:["event","recipe","workout"]}},required:["kind"],additionalProperties:false},annotations:{readOnlyHint:true,untrustedContentHint:false},execute(input:unknown){const kind=(input as {kind?:string})?.kind;if(kind!=="event"&&kind!=="recipe"&&kind!=="workout")throw new Error("Invalid kind");setCurrent({...samples[kind],id:crypto.randomUUID(),checked:samples[kind].checklist.map(()=>false)});return{opened:kind}}},{signal:lifecycle.signal})).catch(()=>undefined);return()=>lifecycle.abort()},[]);
  const completed=actions.filter(a=>a.completed).length;
  function clearCapture(){activeRequest.current?.abort();activeRequest.current=null;if(preview)URL.revokeObjectURL(preview);setLink("");setPreview(null);setFileName("");setCurrent(null);setMessage("");setLoading(false)}
  async function analyzeLink(){if(loading)return;const controller=new AbortController();activeRequest.current=controller;setLoading(true);setMessage("");setCurrent(null);if(preview)URL.revokeObjectURL(preview);setPreview(null);setFileName("");try{const response=await fetch("/api/analyze",{method:"POST",headers:{"Content-Type":"application/json"},signal:controller.signal,body:JSON.stringify({url:link.trim()})});const data=await response.json() as Partial<ActionItem>&{error?:string};if(controller.signal.aborted)return;if(!response.ok)throw new Error(data.error||"This link could not be analyzed.");setCurrent(normalize(data,new URL(link.trim()).hostname))}catch(error){if(!controller.signal.aborted)setMessage(error instanceof Error?error.message:"This link could not be analyzed. Upload a screenshot instead.")}finally{if(activeRequest.current===controller){activeRequest.current=null;setLoading(false)}}}
  function pickedPhoto(input:HTMLInputElement){const file=input.files?.[0];if(file)void analyze(file);input.value=""}
  async function analyze(file:File){if(loading)return;if(!file.type.startsWith("image/")){setMessage("Choose an image from your photo library.");return}if(file.size>MAX_IMAGE_BYTES){setMessage("Keep the photo under 15 MB.");return}if(preview)URL.revokeObjectURL(preview);const controller=new AbortController();activeRequest.current=controller;setPreview(URL.createObjectURL(file));setFileName(file.name);setMessage("");setLoading(true);setCurrent(null);try{const body=new FormData();body.append("image",file);const response=await fetch("/api/analyze",{method:"POST",body,signal:controller.signal});const data=await response.json() as Partial<ActionItem>&{error?:string};if(controller.signal.aborted)return;if(!response.ok)throw new Error(data.error||"Analysis failed");setCurrent(normalize(data,file.name))}catch(e){if(!controller.signal.aborted)setMessage(e instanceof Error?e.message:"The screenshot could not be analyzed.")}finally{if(activeRequest.current===controller){activeRequest.current=null;setLoading(false)}}}
  function openSample(kind:Exclude<ActionKind,"other">){if(loading)return;setCurrent({...samples[kind],id:crypto.randomUUID(),checked:samples[kind].checklist.map(()=>false)});setPreview(null);setFileName("");setMessage("")}
  function updateCurrent(updater:(item:ActionItem)=>ActionItem){setCurrent(v=>v?updater(v):v)}
  function saveCurrent(){if(!current)return;if(!actions.some(a=>a.id===current.id))setActions(items=>[current,...items]);setMessage("Saved to your action board.")}
  function completeCurrent(){if(!current)return;const updated={...current,completed:true,checked:current.checklist.map(()=>true)};setCurrent(updated);setActions(items=>[updated,...items.filter(i=>i.id!==updated.id)]);setMessage("Action completed — attention turned into momentum.")}
  return <main className="app-shell"><header className="topbar"><div className="brand"><span className="brand-mark"><Layers/><span className="logo-spark" aria-hidden="true"/></span><span>feedforward</span></div><nav className="topnav" aria-label="Main navigation"><a className="active" href="#capture">Workspace</a><a href="#board">My action board <span>{actions.length}</span></a></nav><label className="native-photo-button"><ImagePlus/>New capture <ArrowUpRight/><input type="file" disabled={loading} accept="image/*,.heic,.heif" onChange={e=>pickedPhoto(e.currentTarget)}/></label></header>
  <section className="workspace"><div className="intro-row"><div className="intro-copy"><p className="eyebrow"><span className="live-dot"/> FEEDFORWARD / FROM SAVED TO DONE</p><h1>LESS SCROLL.<br/><span>MORE LIFE.</span></h1><p className="intro-description">Good ideas aren’t meant to sit in your camera roll.<br className="desktop-break"/> Turn a screenshot into your next plan.</p><a className="intro-link" href="#capture">Make your next move <ArrowDown/></a></div><aside className="quick-start"><p>PICK YOUR NEXT MOVE</p><button onClick={()=>openSample("recipe")}><span className="quick-icon recipe-icon"><UtensilsCrossed/><span className="icon-detail" aria-hidden="true">✦</span></span><span><strong>MAKE SOMETHING</strong><small>Recipes → shopping lists</small></span><ArrowUpRight/></button><button onClick={()=>openSample("event")}><span className="quick-icon event-icon"><CalendarDays/><span className="icon-detail" aria-hidden="true">＋</span></span><span><strong>GO SOMEWHERE</strong><small>Events → actual plans</small></span><ArrowUpRight/></button><button onClick={()=>openSample("workout")}><span className="quick-icon workout-icon"><Activity/><span className="icon-detail" aria-hidden="true">↗</span></span><span><strong>TRY SOMETHING</strong><small>Workouts → step-by-step routines</small></span><ArrowUpRight/></button></aside></div>
  <div className="section-caption"><span>01 — MAKE IT HAPPEN</span><span>Upload → Review → Save</span></div>
  <div className="flow-grid"><section className="capture-panel" id="capture"><div className="panel-heading"><div><span className="step-number">01</span><p>Add a screenshot</p></div><Badge variant="outline">STEP 01</Badge></div>
  <div className="capture-switch" aria-label="Capture method"><button type="button" aria-pressed={captureMode==="photo"} disabled={loading} onClick={()=>setCaptureMode("photo")}><ImagePlus/>Upload photo</button><button type="button" aria-pressed={captureMode==="link"} disabled={loading} onClick={()=>setCaptureMode("link")}><Link2/>Paste link</button></div>
  {(link||preview||current||message||loading)&&<div className="capture-clear-row"><button type="button" onClick={clearCapture} className="capture-clear"><X/>Clear {captureMode==="link"?"link":"upload"}</button></div>}
  {captureMode==="link"?<form className="link-form" onSubmit={e=>{e.preventDefault();void analyzeLink()}}><span className="link-form-icon"><Link2/></span><h3>Found it online?</h3><p>Paste a public TikTok, Instagram, or website link.</p><label htmlFor="post-link">Post URL</label><input id="post-link" type="url" required maxLength={4096} placeholder="https://…" value={link} onChange={e=>setLink(e.target.value)} disabled={loading} autoComplete="off"/><button className="link-submit" type="submit" disabled={loading||!link.trim()}>{loading?<><RefreshCw className="link-spinner"/>Reading your link…</>:<>Find my next step <ArrowUpRight/></>}</button><small role="status">{loading?"Retrieving public details and building your plan…":"Private or unavailable post? Upload a screenshot instead."}</small></form>:
  <label className={`drop-zone ${dragging?"dragging":""}`} onDragOver={e=>{e.preventDefault();setDragging(true)}} onDragLeave={()=>setDragging(false)} onDrop={e=>{e.preventDefault();setDragging(false);const f=e.dataTransfer.files[0];if(f)analyze(f)}}><input type="file" disabled={loading} accept="image/*,.heic,.heif" aria-label="Choose a photo from your library" onChange={e=>pickedPhoto(e.currentTarget)}/>{preview?<img src={preview} alt="Photo selected for analysis"/>:<div className="drop-copy"><span className="upload-illustration"><ScanLine/><span className="upload-badge"><UploadCloud/></span></span><strong>Drop your screenshot here</strong><small>Drop an image here, or click to browse</small><span className="browse-pill">Choose a screenshot <ArrowUpRight/></span><small className="file-hint">Photos & screenshots · Up to 15 MB</small></div>}{loading&&<div className="analyzing"><RefreshCw/><strong>Finding the next step…</strong><span>Reading context, dates, and useful details</span></div>}</label>}
  {fileName&&!loading&&<div className="file-row"><ImagePlus/><span>{fileName}</span></div>}{message&&<p role="status" className={`status-message ${message.startsWith("Saved")||message.startsWith("Action")?"success":""}`}>{message}</p>}
  <div className="sample-block"><div><span>NO SCREENSHOT?</span><p>Explore an example</p></div><div className="sample-buttons"><button onClick={()=>openSample("event")}><CalendarDays/>Event</button><button onClick={()=>openSample("recipe")}><ShoppingBasket/>Recipe</button><button onClick={()=>openSample("workout")}><Activity/>Workout</button></div></div></section>
  <section className="result-panel"><div className="panel-heading"><div><span className="step-number">02</span><p>The useful part</p></div><span className="privacy-note">STEP 02</span></div>{current?<div className="result-stack"><ActionCard item={current} onToggleStep={i=>updateCurrent(item=>({...item,checked:item.checked.map((v,n)=>n===i?!v:v)}))} onComplete={completeCurrent}/><Button variant="outline" className="save-button" onClick={saveCurrent}><ListChecks/>Save to action board</Button></div>:<div className="empty-result"><div className="preview-kicker"><span/> TRY IT OUT</div><div className="demo-card"><div className="demo-card-top"><span className="demo-icon"><UtensilsCrossed/></span><span>FROM “SAVED” TO “SERVED”<small>Your next favorite dinner</small></span><ArrowUpRight/></div><h3>Chili crisp noodles.<br/>Dinner, sorted.</h3><div className="demo-tags"><span><Clock3/>15 minutes</span><span><ShoppingBasket/>6 ingredients</span></div><div className="demo-check"><span><Check/></span>A shopping list, ready to go</div><button onClick={()=>openSample("recipe")}>Explore this example <ArrowUpRight/></button></div><div className="preview-caption"><WandSparkles/><p>The details, pulled together.<br/><strong>Ready when you are.</strong></p></div><div className="mini-flow"><span>Capture</span><i/><span>Make a plan</span><i/><span>Go live it</span></div></div>}</section></div>
  <section className="board-section" id="board"><div className="board-heading"><div><p className="eyebrow">Action board</p><h2>THE LINEUP.</h2></div><span>{actions.length?`${completed} of ${actions.length} completed`:"Saved actions stay on this device"}</span></div><Tabs defaultValue="all"><TabsList variant="line"><TabsTrigger value="all">All actions <span className="tab-count">{actions.length}</span></TabsTrigger><TabsTrigger value="open">Open</TabsTrigger><TabsTrigger value="done">Completed</TabsTrigger></TabsList>{(["all","open","done"] as const).map(filter=>{const filtered=actions.filter(item=>filter==="all"||(filter==="done"?item.completed:!item.completed));return <TabsContent key={filter} value={filter} className="board-grid">{filtered.length?filtered.map(item=><ActionCard key={item.id} item={item} onToggleStep={i=>setActions(items=>items.map(v=>v.id===item.id?{...v,checked:v.checked.map((c,n)=>n===i?!c:c)}:v))} onComplete={()=>setActions(items=>items.map(v=>v.id===item.id?{...v,completed:true,checked:v.checklist.map(()=>true)}:v))} onRemove={()=>setActions(items=>items.filter(v=>v.id!==item.id))}/>):<div className="board-empty"><span className="empty-board-icon"><Bookmark/></span><div><h3>{actions.length?"All clear here.":"Keep your good finds together."}</h3><p>{actions.length?"Switch tabs to see your other actions.":"Your saved plans and lists will appear here."}</p></div><a href="#capture">{actions.length?"Capture another":"Create your first action"}<ArrowUpRight/></a></div>}</TabsContent>})}</Tabs></section></section><footer><span className="footer-brand"><Layers/> feedforward <span>A little more useful.</span></span><span className="footer-privacy"><ShieldCheck/> Your board stays on this device</span></footer></main>}
